import { sortTeamsFunc } from "@/store.js";

const sortTeamsFuncInput = [
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "East",
    Team: "WAS",
    Name: "Washington Redskins",
    Wins: 3,
    Losses: 13,
    Ties: 0,
    Percentage: 0.188,
    PointsFor: 266,
    PointsAgainst: 435,
    NetPoints: -169,
    Touchdowns: 28,
    DivisionWins: 0,
    DivisionLosses: 6,
    ConferenceWins: 2,
    ConferenceLosses: 10,
    TeamID: 35,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 35,
  },
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "West",
    Team: "SEA",
    Name: "Seattle Seahawks",
    Wins: 11,
    Losses: 5,
    Ties: 0,
    Percentage: 0.688,
    PointsFor: 405,
    PointsAgainst: 398,
    NetPoints: 7,
    Touchdowns: 49,
    DivisionWins: 3,
    DivisionLosses: 3,
    ConferenceWins: 8,
    ConferenceLosses: 4,
    TeamID: 30,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 30,
  },
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "North",
    Team: "CHI",
    Name: "Chicago Bears",
    Wins: 8,
    Losses: 8,
    Ties: 0,
    Percentage: 0.5,
    PointsFor: 280,
    PointsAgainst: 298,
    NetPoints: -18,
    Touchdowns: 30,
    DivisionWins: 4,
    DivisionLosses: 2,
    ConferenceWins: 7,
    ConferenceLosses: 5,
    TeamID: 6,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 6,
  },
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "North",
    Team: "GB",
    Name: "Green Bay Packers",
    Wins: 13,
    Losses: 3,
    Ties: 0,
    Percentage: 0.813,
    PointsFor: 376,
    PointsAgainst: 313,
    NetPoints: 63,
    Touchdowns: 44,
    DivisionWins: 6,
    DivisionLosses: 0,
    ConferenceWins: 10,
    ConferenceLosses: 2,
    TeamID: 12,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 12,
  },

  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "West",
    Team: "SF",
    Name: "San Francisco 49ers",
    Wins: 13,
    Losses: 3,
    Ties: 0,
    Percentage: 0.813,
    PointsFor: 479,
    PointsAgainst: 310,
    NetPoints: 169,
    Touchdowns: 56,
    DivisionWins: 5,
    DivisionLosses: 1,
    ConferenceWins: 10,
    ConferenceLosses: 2,
    TeamID: 31,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 31,
  },
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "South",
    Team: "NO",
    Name: "New Orleans Saints",
    Wins: 13,
    Losses: 3,
    Ties: 0,
    Percentage: 0.813,
    PointsFor: 458,
    PointsAgainst: 341,
    NetPoints: 117,
    Touchdowns: 52,
    DivisionWins: 5,
    DivisionLosses: 1,
    ConferenceWins: 9,
    ConferenceLosses: 3,
    TeamID: 22,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 22,
  },
];

const sortTeamsFuncOutput = [
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "North",
    Team: "GB",
    Name: "Green Bay Packers",
    Wins: 13,
    Losses: 3,
    Ties: 0,
    Percentage: 0.813,
    PointsFor: 376,
    PointsAgainst: 313,
    NetPoints: 63,
    Touchdowns: 44,
    DivisionWins: 6,
    DivisionLosses: 0,
    ConferenceWins: 10,
    ConferenceLosses: 2,
    TeamID: 12,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 12,
  },

  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "West",
    Team: "SF",
    Name: "San Francisco 49ers",
    Wins: 13,
    Losses: 3,
    Ties: 0,
    Percentage: 0.813,
    PointsFor: 479,
    PointsAgainst: 310,
    NetPoints: 169,
    Touchdowns: 56,
    DivisionWins: 5,
    DivisionLosses: 1,
    ConferenceWins: 10,
    ConferenceLosses: 2,
    TeamID: 31,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 31,
  },
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "South",
    Team: "NO",
    Name: "New Orleans Saints",
    Wins: 13,
    Losses: 3,
    Ties: 0,
    Percentage: 0.813,
    PointsFor: 458,
    PointsAgainst: 341,
    NetPoints: 117,
    Touchdowns: 52,
    DivisionWins: 5,
    DivisionLosses: 1,
    ConferenceWins: 9,
    ConferenceLosses: 3,
    TeamID: 22,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 22,
  },
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "West",
    Team: "SEA",
    Name: "Seattle Seahawks",
    Wins: 11,
    Losses: 5,
    Ties: 0,
    Percentage: 0.688,
    PointsFor: 405,
    PointsAgainst: 398,
    NetPoints: 7,
    Touchdowns: 49,
    DivisionWins: 3,
    DivisionLosses: 3,
    ConferenceWins: 8,
    ConferenceLosses: 4,
    TeamID: 30,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 30,
  },
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "North",
    Team: "CHI",
    Name: "Chicago Bears",
    Wins: 8,
    Losses: 8,
    Ties: 0,
    Percentage: 0.5,
    PointsFor: 280,
    PointsAgainst: 298,
    NetPoints: -18,
    Touchdowns: 30,
    DivisionWins: 4,
    DivisionLosses: 2,
    ConferenceWins: 7,
    ConferenceLosses: 5,
    TeamID: 6,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 6,
  },
  {
    SeasonType: 1,
    Season: 2019,
    Conference: "NFC",
    Division: "East",
    Team: "WAS",
    Name: "Washington Redskins",
    Wins: 3,
    Losses: 13,
    Ties: 0,
    Percentage: 0.188,
    PointsFor: 266,
    PointsAgainst: 435,
    NetPoints: -169,
    Touchdowns: 28,
    DivisionWins: 0,
    DivisionLosses: 6,
    ConferenceWins: 2,
    ConferenceLosses: 10,
    TeamID: 35,
    DivisionTies: 0,
    ConferenceTies: 0,
    GlobalTeamID: 35,
  },
];

test("sortTeamsFunc", () => {
  expect(
    sortTeamsFunc(sortTeamsFuncInput, "Wins", "DivisionWins", "ConferenceWins")
  ).toEqual(sortTeamsFuncOutput);
});
